<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="AMICHAITO1-HHS" ignored="1" name="Automated test - End2End" tests="12" failures="12" timestamp="29 Jul 2019 13:33:38 GMT" time="309.885" errors="0">
  <testcase name="initialOfferQuestions" time="34.811" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed in FIRST OFFER QUESTIONS.">
      <![CDATA[java.lang.Exception: Failed in FIRST OFFER QUESTIONS.
at TestNG.sanityAllOptionsTest.initialOfferQuestions(sanityAllOptionsTest.java:280)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- initialOfferQuestions -->
  <testcase name="callMeWizard1" time="37.297" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed in ***Call me wizard 1***">
      <![CDATA[java.lang.Exception: Failed in ***Call me wizard 1***
at TestNG.sanityAllOptionsTest.callMeWizard1(sanityAllOptionsTest.java:327)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- callMeWizard1 -->
  <testcase name="initialOfferScreen" time="32.219" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed in INITIAL OFFER SCREEN QUESTION">
      <![CDATA[java.lang.Exception: Failed in INITIAL OFFER SCREEN QUESTION
at TestNG.sanityAllOptionsTest.initialOfferScreen(sanityAllOptionsTest.java:415)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- initialOfferScreen -->
  <testcase name="finalOfferQuestions" time="30.259" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed in FINAL OFFER QUESTIONS">
      <![CDATA[java.lang.Exception: Failed in FINAL OFFER QUESTIONS
at TestNG.sanityAllOptionsTest.finalOfferQuestions(sanityAllOptionsTest.java:636)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- finalOfferQuestions -->
  <testcase name="finalOfferScreen" time="30.202" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed in FINAL OFFER screen">
      <![CDATA[java.lang.Exception: Failed in FINAL OFFER screen
at TestNG.sanityAllOptionsTest.finalOfferScreen(sanityAllOptionsTest.java:691)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- finalOfferScreen -->
  <testcase name="covers" time="30.291" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed in COVERS screen">
      <![CDATA[java.lang.Exception: Failed in COVERS screen
at TestNG.sanityAllOptionsTest.covers(sanityAllOptionsTest.java:774)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- covers -->
  <testcase name="payments" time="31.241" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed in PAYMENTS screen">
      <![CDATA[java.lang.Exception: Failed in PAYMENTS screen
at TestNG.sanityAllOptionsTest.payments(sanityAllOptionsTest.java:824)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- payments -->
  <testcase name="returnSteps" time="0.017" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed in moveing BACKWARD">
      <![CDATA[java.lang.Exception: Failed in moveing BACKWARD
at TestNG.sanityAllOptionsTest.returnSteps(sanityAllOptionsTest.java:951)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- returnSteps -->
  <testcase name="forwardSteps" time="4.106" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed in moveing FORWARD">
      <![CDATA[java.lang.Exception: Failed in moveing FORWARD
at TestNG.sanityAllOptionsTest.forwardSteps(sanityAllOptionsTest.java:1038)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- forwardSteps -->
  <testcase name="iframeCreditGuard" time="40.198" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed in Iframe CreditGuard">
      <![CDATA[java.lang.Exception: Failed in Iframe CreditGuard
at TestNG.sanityAllOptionsTest.iframeCreditGuard(sanityAllOptionsTest.java:1085)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- iframeCreditGuard -->
  <testcase name="thankYouPage" time="35.194" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed to display thank you page">
      <![CDATA[java.lang.Exception: Failed to display thank you page
at TestNG.sanityAllOptionsTest.thankYouPage(sanityAllOptionsTest.java:1102)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- thankYouPage -->
  <testcase name="registeredAccount" time="4.015" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed to display thank you page">
      <![CDATA[java.lang.Exception: Failed to display thank you page
at TestNG.sanityAllOptionsTest.registeredAccount(sanityAllOptionsTest.java:1123)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- registeredAccount -->
  <testcase name="callMeWizard2" time="0.0" classname="TestNG.sanityAllOptionsTest">
    <ignored/>
  </testcase> <!-- callMeWizard2 -->
</testsuite> <!-- Automated test - End2End -->
