<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="AMICHAITO1-HHS" ignored="1" name="Test-class test 5 redYearsOfInsurance" tests="12" failures="11" timestamp="30 Jul 2019 17:16:28 GMT" time="294.038" errors="0">
  <testcase name="initialOfferQuestions" time="21.546" classname="TestNG.sanityAllOptionsTest"/>
  <testcase name="callMeWizard1" time="37.183" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed in ***Call me wizard 1***">
      <![CDATA[java.lang.Exception: Failed in ***Call me wizard 1***
at TestNG.sanityAllOptionsTest.callMeWizard1(sanityAllOptionsTest.java:327)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- callMeWizard1 -->
  <testcase name="initialOfferScreen" time="32.153" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed in INITIAL OFFER SCREEN QUESTION">
      <![CDATA[java.lang.Exception: Failed in INITIAL OFFER SCREEN QUESTION
at TestNG.sanityAllOptionsTest.initialOfferScreen(sanityAllOptionsTest.java:415)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- initialOfferScreen -->
  <testcase name="finalOfferQuestions" time="30.192" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed in FINAL OFFER QUESTIONS">
      <![CDATA[java.lang.Exception: Failed in FINAL OFFER QUESTIONS
at TestNG.sanityAllOptionsTest.finalOfferQuestions(sanityAllOptionsTest.java:653)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- finalOfferQuestions -->
  <testcase name="finalOfferScreen" time="30.166" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed in FINAL OFFER screen">
      <![CDATA[java.lang.Exception: Failed in FINAL OFFER screen
at TestNG.sanityAllOptionsTest.finalOfferScreen(sanityAllOptionsTest.java:708)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- finalOfferScreen -->
  <testcase name="covers" time="30.194" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed in COVERS screen">
      <![CDATA[java.lang.Exception: Failed in COVERS screen
at TestNG.sanityAllOptionsTest.covers(sanityAllOptionsTest.java:791)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- covers -->
  <testcase name="payments" time="31.182" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed in PAYMENTS screen">
      <![CDATA[java.lang.Exception: Failed in PAYMENTS screen
at TestNG.sanityAllOptionsTest.payments(sanityAllOptionsTest.java:841)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- payments -->
  <testcase name="returnSteps" time="0.018" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed in moveing BACKWARD">
      <![CDATA[java.lang.Exception: Failed in moveing BACKWARD
at TestNG.sanityAllOptionsTest.returnSteps(sanityAllOptionsTest.java:968)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- returnSteps -->
  <testcase name="forwardSteps" time="2.032" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed in moveing FORWARD">
      <![CDATA[java.lang.Exception: Failed in moveing FORWARD
at TestNG.sanityAllOptionsTest.forwardSteps(sanityAllOptionsTest.java:1055)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- forwardSteps -->
  <testcase name="iframeCreditGuard" time="40.175" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed in Iframe CreditGuard">
      <![CDATA[java.lang.Exception: Failed in Iframe CreditGuard
at TestNG.sanityAllOptionsTest.iframeCreditGuard(sanityAllOptionsTest.java:1102)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- iframeCreditGuard -->
  <testcase name="thankYouPage" time="35.141" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed to display thank you page">
      <![CDATA[java.lang.Exception: Failed to display thank you page
at TestNG.sanityAllOptionsTest.thankYouPage(sanityAllOptionsTest.java:1119)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- thankYouPage -->
  <testcase name="registeredAccount" time="4.017" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed to display thank you page">
      <![CDATA[java.lang.Exception: Failed to display thank you page
at TestNG.sanityAllOptionsTest.registeredAccount(sanityAllOptionsTest.java:1140)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- registeredAccount -->
  <testcase name="callMeWizard2" time="0.0" classname="TestNG.sanityAllOptionsTest">
    <ignored/>
  </testcase> <!-- callMeWizard2 -->
</testsuite> <!-- Test-class test 5 redYearsOfInsurance -->
